"""output/email_sender.py — Sends HTML MOM email via SMTP (Gmail TLS)."""

import smtplib
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.utils import formataddr
from datetime import date

from config.settings import (
    SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD,
    EMAIL_FROM_NAME, EMAIL_RECIPIENTS,
)

logger = logging.getLogger(__name__)


class EmailSender:
    """Dispatches HTML MOM emails via SMTP."""

    def send(self, mom_data: dict, html_body: str) -> bool:
        subject = (
            f"[MOM] {mom_data.get('meeting_title', 'Meeting')} — "
            f"{mom_data.get('date', date.today().strftime('%d-%b-%Y'))}"
        )
        plain_text = self._build_plain_text(mom_data)

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"]    = formataddr((EMAIL_FROM_NAME, SMTP_USER))
        msg["To"]      = ", ".join(EMAIL_RECIPIENTS)
        msg.attach(MIMEText(plain_text, "plain", "utf-8"))
        msg.attach(MIMEText(html_body,  "html",  "utf-8"))

        try:
            with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=30) as server:
                server.ehlo(); server.starttls(); server.ehlo()
                server.login(SMTP_USER, SMTP_PASSWORD)
                server.sendmail(SMTP_USER, EMAIL_RECIPIENTS, msg.as_string())
            logger.info(f"[Email] Sent to: {', '.join(EMAIL_RECIPIENTS)}")
            return True
        except smtplib.SMTPException as e:
            logger.error(f"[Email] SMTP error: {e}")
            return False

    def _build_plain_text(self, mom_data: dict) -> str:
        lines = [
            f"MINUTES OF MEETING — {mom_data.get('meeting_title', 'N/A')}",
            f"Date: {mom_data.get('date', 'N/A')}",
            f"Context: {mom_data.get('meeting_context', 'N/A')}",
            "", "EXECUTIVE SUMMARY", mom_data.get("executive_summary", "N/A"),
            "", "KEY DECISIONS",
        ]
        for i, d in enumerate(mom_data.get("key_decisions", []), 1):
            lines.append(f"  {i}. {d}")
        lines += ["", "ACTION ITEMS"]
        for i, item in enumerate(mom_data.get("action_items", []), 1):
            lines.append(
                f"  {i}. [{item.get('priority','?')}] {item.get('task','?')} "
                f"→ {item.get('assignee','?')} by {item.get('deadline','TBD')}"
            )
        lines += ["", "NEXT STEPS", mom_data.get("next_steps", "N/A"), "",
                  "---", "Auto-generated by MOM Generator"]
        return "\n".join(lines)
